defaultEntryPoints = ["https","http"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[acme]
email = "juande.mc@coretest.redyser.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
  main = "coretest.redyser.com"



[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "coretest.redyser.com"
watch = true
exposedbydefault = false
