defaultEntryPoints = ["http", "https"]

[web]
address = ":8090"

[entryPoints]

[entryPoints.http]
address = ":80"

[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

[acme]
email = "juande.mc@redyser.com"
storage = "acme.json"
entryPoint = "https"
[acme.httpChallenge]
    entryPoint = "http"
onDemand = true
OnHostRule = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "coretest.redyser.com"
watch = true
exposedbydefault = false
